#
# Makefile for misc devices that really don't fit anywhere else.
#
#include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y += hx8394f_hdp_dsi_vdo_oncell_txd.o
ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
ccflags-$(CONFIG_PRIZE_LCD_BIAS_TPS65132) += -I$(srctree)/drivers/misc/mediatek/prize/lcdbias/tps65132


