ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/barometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/hwmon/include
ccflags-$(CONFIG_DMADEVICES_DEBUG)  := -DDEBUG

obj-y	:=  SPL07.o
