
sitronix-ts-objs	= sitronix_ts.o sitronix_st7123_i2c.o sitronix_st7123_spi.o sitronix_st7123_utility.o sitronix_st7123_mt.o sitronix_st7123_nodes.o sitronix_st7123_upgrade.o sitronix_st7123_test.o
obj-y += sitronix-ts.o

